import type { Edge, Node } from "@xyflow/react";

// ============================================
// SOP (Standard Operating Procedure) types
// ============================================
// Mirrors the backend `SOPPlan` / `SOPStep` models
// (src/agents/team_agent/sop/schemas.py). The plan is generated by the main
// agent via the `update_sop` tool: steps are DAG nodes, dependencies are edges.
//
// `normalizeSopEvent` tolerates backend field aliases and NEVER casts arbitrary
// strings into the status unions — unknown values fall back to safe defaults.

export type SopStepStatus =
  | "pending"
  | "running"
  | "succeeded"
  | "failed"
  | "cancelled";

export type SopPlanStatus =
  | "draft"
  | "awaiting_confirmation"
  | "running"
  | "completed"
  | "failed"
  | "cancelled"
  | "rejected"
  | "timed_out";

export interface SopStep {
  step_id: string;
  title: string;
  description?: string;
  /** 上游依赖的 step_id（前端据此建边） */
  dependencies: string[];
  /** 负责角色 subagent_type */
  assignee: string;
  stage?: string | null;
  /** 本步可验证的交付物说明 */
  expected_output: string;
  acceptance_criteria?: string[];
  status: SopStepStatus;
  attempts?: number;
  /** 步骤完成摘要（主代理回填） */
  output?: string | null;
  error?: string | null;
}

export interface SopPlan {
  plan_id: string;
  session_id?: string;
  team_id?: string;
  goal: string;
  summary?: string;
  steps: SopStep[];
  status: SopPlanStatus;
  user_feedback?: string | null;
  created_at?: string;
  updated_at?: string;
  /** 前端扩展：sop_plan 审批 ID（来自 approval_required 事件），确认/重新规划按钮依赖 */
  approval_id?: string;
  approval_expires_at?: string | null;
}

/** SOP 步骤节点（React Flow node）的数据载荷。 */
export interface SopNodeData {
  title: string;
  status: SopStepStatus;
  assignee: string;
  description: string;
  expectedOutput: string;
  error: string | null;
  stepIndex: number;
  /** 估算的节点渲染高度（供 dagre 布局使用） */
  height?: number;
  [key: string]: unknown;
}

export interface SopFlowNode extends Node<SopNodeData> {
  type: "sop";
}

export interface SopFlowEdge extends Edge {
  type: "smoothstep";
}

// ============================================
// Normalizers / reducers
// ============================================

const SOP_STEP_STATUSES: ReadonlySet<string> = new Set([
  "pending",
  "running",
  "succeeded",
  "failed",
  "cancelled",
]);

const SOP_PLAN_STATUSES: ReadonlySet<string> = new Set([
  "draft",
  "awaiting_confirmation",
  "running",
  "completed",
  "failed",
  "cancelled",
  "rejected",
  "timed_out",
]);

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function asString(value: unknown): string | undefined {
  return typeof value === "string" ? value : undefined;
}

function asNullableString(value: unknown): string | null | undefined {
  if (typeof value === "string") return value;
  if (value === null || value === undefined) return value;
  return undefined;
}

function asNumber(value: unknown): number | undefined {
  return typeof value === "number" && Number.isFinite(value) ? value : undefined;
}

function asStringArray(value: unknown): string[] {
  if (!Array.isArray(value)) return [];
  return value.filter((item): item is string => typeof item === "string");
}

function normalizeSopStepStatus(value: unknown): SopStepStatus {
  if (typeof value === "string" && SOP_STEP_STATUSES.has(value)) {
    return value as SopStepStatus;
  }
  return "pending";
}

function normalizeSopPlanStatus(value: unknown): SopPlanStatus {
  if (typeof value === "string" && SOP_PLAN_STATUSES.has(value)) {
    return value as SopPlanStatus;
  }
  return "draft";
}

function normalizeSopStep(raw: Record<string, unknown>): SopStep | null {
  const stepId = asString(raw.step_id) ?? asString(raw.id);
  if (!stepId) return null;
  return {
    step_id: stepId,
    title: asString(raw.title) ?? stepId,
    description: asString(raw.description) ?? "",
    dependencies: asStringArray(raw.dependencies),
    assignee: asString(raw.assignee) ?? "",
    stage: asNullableString(raw.stage) ?? null,
    expected_output:
      asString(raw.expected_output) ??
      asString(raw.expectedOutput) ??
      "",
    acceptance_criteria: asStringArray(raw.acceptance_criteria),
    status: normalizeSopStepStatus(raw.status),
    attempts: asNumber(raw.attempts) ?? 0,
    output: asNullableString(raw.output) ?? null,
    error: asNullableString(raw.error) ?? null,
  };
}

/**
 * Normalize a raw SOP payload into a typed SopPlan.
 *
 * Accepts either:
 * - `sop:updated` snapshot (the payload IS the plan), or
 * - `approval_required` data `{ id, message, type: "sop_plan", plan_id, plan }`
 *   (nested `plan` snapshot + `id` captured as `approval_id`).
 *
 * Returns null when the payload is not a valid plan (no plan id / no steps).
 */
export function normalizeSopEvent(payload: unknown): SopPlan | null {
  if (!isRecord(payload)) return null;

  const nested = isRecord(payload.plan) ? payload.plan : null;
  const source = nested ?? payload;

  const planId =
    asString(source.plan_id) ??
    asString(source.id) ??
    asString(source.planId);
  if (!planId) return null;
  if (!Array.isArray(source.steps)) return null;

  const steps: SopStep[] = [];
  for (const rawStep of source.steps) {
    if (!isRecord(rawStep)) return null;
    const step = normalizeSopStep(rawStep);
    if (!step) return null;
    steps.push(step);
  }

  return {
    plan_id: planId,
    session_id: asString(source.session_id) ?? undefined,
    team_id: asString(source.team_id) ?? undefined,
    goal: asString(source.goal) ?? "",
    summary: asString(source.summary) ?? undefined,
    steps,
    status: normalizeSopPlanStatus(source.status),
    user_feedback: asNullableString(source.user_feedback) ?? null,
    created_at: asString(source.created_at) ?? undefined,
    updated_at: asString(source.updated_at) ?? undefined,
    // Only the approval_required shape carries an approval id (its payload has
    // a nested `plan`). A bare snapshot must never be mistaken for one.
    approval_id:
      (nested ? asString(payload.id) : undefined) ??
      asString(source.approval_id) ??
      asString(source.approvalId),
    approval_expires_at:
      asString(source.approval_expires_at) ??
      asString(source.approvalExpiresAt) ??
      null,
  };
}

/**
 * Reduce SOP state from an event.
 *
 * `event` may be:
 * - a raw payload (sop:updated snapshot or approval_required data), or
 * - an envelope `{ event_type, data }` (SSE event / HistoryEvent).
 *
 * Semantics: full snapshot replacement (same as `todo:updated`). The only
 * exception is the frontend-only `approval_id`, which is preserved from the
 * current state when the incoming snapshot does not carry it (SSE event order
 * is not guaranteed between `sop:updated` and `approval_required`).
 */
export function reduceSop(current: SopPlan | null, event: unknown): SopPlan | null {
  if (!isRecord(event)) return current;
  const payload =
    typeof event.event_type === "string" && isRecord(event.data)
      ? event.data
      : event;
  const next = normalizeSopEvent(payload);
  if (!next) return current;
  if (
    !next.approval_id &&
    current?.approval_id &&
    current.plan_id === next.plan_id
  ) {
    next.approval_id = current.approval_id;
  }
  return next;
}

/** True when a history event can rebuild the SOP card (full-snapshot events). */
export function isSopReplayEvent(event: unknown): boolean {
  if (!isRecord(event)) return false;
  if (event.event_type === "sop:updated") return true;
  if (event.event_type !== "approval_required") return false;
  const data = isRecord(event.data) ? event.data : event;
  return data.type === "sop_plan" || data.approval_type === "sop_plan";
}
